title: <p align="center"> Huynh Viet Cuong </p>
logo: /images/me.jpg

description:
  <p align="center">
  <a href="pdf/Huynh-Viet-Cuong.pdf">Resume</a> |
  <a href="https://github.com/cuonghv0298">GitHub</a>
  
  <br>   
  I'm working on Data Science, Computer Vision & NLP related problems.
  Working in map and commercial domain for 1 years.
  <br>
  </p>



theme: jekyll-theme-minimal